# 3) Write a python program to display IMDB’s Top rated 50 Indian movies’ data (i.e. name, rating, year of release) and make data frame.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
page = requests.get("https://www.imdb.com/india/top-rated-indian-movies/")

In [3]:
page

In [4]:
# Send a GET request to IMDb's top rated Indian movies page
url = "https://www.imdb.com/india/top-rated-indian-movies/"
response = requests.get(url)

In [5]:
# Use BeautifulSoup to parse the HTML content of the response
soup = BeautifulSoup(response.content, "html.parser")

In [6]:
# Find the table that contains the top 50 rated Indian movies
table = soup.find("tbody", {"class": "lister-list"})

In [7]:
# Extract the data for each movie in the table
movies = []
for row in table.find_all("tr")[0:50]:
    movie = {}
    movie["Name"] = row.find("td", {"class": "titleColumn"}).a.text
    movie["Rating"] = float(row.find("strong").text)
    movie["Year of release"] = int(row.find("span", {"class": "secondaryInfo"}).text[1:5])
    movies.append(movie)

In [8]:
# Create a Pandas DataFrame to store the results
df = pd.DataFrame(movies)

In [9]:
# Display the DataFrame
df

                                   Name  Rating  Year of release
0   Ramayana: The Legend of Prince Rama     8.5             1993
1            Rocketry: The Nambi Effect     8.4             2022
2                               Nayakan     8.4             1987
3                              Gol Maal     8.4             1979
4                            Anbe Sivam     8.4             2003
5                           777 Charlie     8.4             2022
6                              Jai Bhim     8.4             2021
7                     Pariyerum Perumal     8.4             2018
8                              3 Idiots     8.4             2009
9                           Apur Sansar     8.4             1959
10                     Manichitrathazhu     8.4             1993
11                                #Home     8.3             2021
12                      Soorarai Pottru     8.3             2020
13                         Black Friday     8.3             2004
14                    Kumbalangi Nights     8.3             2019
15                    C/o Kancharapalem     8.3             2018
16                     Taare Zameen Par     8.3             2007
17                             Kireedam     8.3             1989
18                               Dangal     8.3             2016
19                               Kaithi     8.3             2019
20                               Jersey     8.3             2019
21                                   96     8.3             2018
22                          Maya Bazaar     8.2             1957
23                            Natsamrat     8.2             2016
24                               Asuran     8.2             2019
25                           Drishyam 2     8.2             2021
26                           Sita Ramam     8.2             2022
27                         Thevar Magan     8.2             1992
28                           Visaaranai     8.2             2015
29                  Sarpatta Parambarai     8.2             2021
30                           Thalapathi     8.2             1991
31                      Pather Panchali     8.2             1955
32                         Nadodikkattu     8.2             1987
33                             Drishyam     8.2             2013
34                   Jaane Bhi Do Yaaro     8.2             1983
35                         Thani Oruvan     8.2             2015
36                         Sardar Udham     8.2             2021
37                            Aparajito     8.2             1956
38                         Vada Chennai     8.2             2018
39                    Khosla Ka Ghosla!     8.2             2006
40                              Anniyan     8.1             2005
41                             Ratsasan     8.1             2018
42                        Chupke Chupke     8.1             1975
43                   Gangs of Wasseypur     8.1             2012
44                              Peranbu     8.1             2018
45                             Drishyam     8.1             2015
46                             Mahanati     8.1             2018
47                       Bangalore Days     8.1             2014
48                                Satya     8.1             1998
49          Agent Sai Srinivasa Athreya     8.1             2019